site_name: PicoChess
site_url: http://docs.picochess.org/
repo_url: https://github.com/jromang/picochess
docs_dir: docs

pages:

# Introduction:
- ['index.md', 'Home']

# User Guide:
- ['manual.md', 'Manual']
