name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r test-requirements.txt
  pylama:
    needs: build
    runs-on: ubuntu-latest
   
    steps:
    - name: Analysing the code with pylama
      run: |
        pylama
  unittest:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Run unit tests
      run: |
        python -m unittest
